services:
  # postgres:
  #   image: postgres:15.1
  #   volumes:
  #     - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  #     - postgres_microservice_back:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: people
  #     POSTGRES_PASSWORD: people
  #     POSTGRES_DB: people
  #   restart: unless-stopped
  #   ports:
  #     - 5445:5432

  # back:
  #   build: service_name/
  #   #like ais_mfr_contacts/
  #   environment:
  #     - ENV
  #   command: npm run start:${ENV:-test}
  #   ports:
  #     - 48150:80
  #   depends_on:
  #     - postgres

  front:
    build: frontend_name/.
    labels:
      SERVICE_CHECK_INTERVAL: 10s
    ports:
      - 50125:80
    # depends_on:
    #   - back
volumes:
  postgres_microservice_back:
